### ISSUE TITLE
Use of descendants in initialization doesn't work outside of Rails

### ISSUE THREAD

**Issue by danmelnick** [taylorbrooks/closeio#15]
Hi there,

Thanks for the awesome gem! I'm excited to use it.

Using your gem outside of Rails blows up because you're relying on activesupport/lib/active_support/core_ext/class/subclasses to call .descendants in the initialization.

I don't know how you view the Gem, but would you be open to either not using .descendants or adding an explicit dependency on this class? 

I'm happy to submit a pull request for either depending on what you want to do.

Thanks!

**Comment by hoopsho** [comment]
I was able to get it to work in a ruby script using the following as a starting point:

#!/usr/bin/ruby
require 'rubygems'
require 'active_support/core_ext/class/subclasses'
require 'closeio'
Closeio.configure("<API_KEY>")
lead = Closeio::Lead.find('<LEAD_ID>')
puts lead.name

I also used bundler with the following Gemfile:
source 'https://rubygems.org'

gem 'closeio'
gem 'activesupport'


Again, just a starting point that might help you.

**Comment by danmelnick** [comment]
Hi @hoopsho — right, I was able to do the same. I'm just pointing out that if it's a dependency it should be made explicit.

**Comment by taylorbrooks** [comment]
@hoopsho @danmelnick Good point. 

Do either of you have a preference on removing the dependency on `activesupport` or moving this inline like?

````ruby
def self.descendants
  ObjectSpace.each_object(Class).select { |klass| klass < self }
end
````

**Comment by danmelnick** [comment]
I'd prefer to remove the dependency, so I'd vote for pure Ruby.

**Comment by taylorbrooks** [comment]
I feel like I'm taking crazy pills...

I pushed this https://github.com/taylorbrooks/closeio/commit/2d308159ad87799a5558166979cb49aa4601e40d, which should fix it, but I'm getting this error: 

````sh
undefined method `descendants' for Closeio::Base:Class (NoMethodError)
````

What am I missing that's obvious?

**Comment by taylorbrooks** [comment]
Releasing a new version of the gem that makes this moot.
