### ISSUE TITLE
Find leads by custom field with space

### ISSUE THREAD

**Issue by michaelimstepf** [taylorbrooks/closeio#27]
Hey Taylor,

We have custom fields with white spaces and I can't query by them.

Example:

```ruby
client.list_leads("custom.Paused:false") # works
client.list_leads("custom.Multiple once off:false") # doesn't work
```

I wonder whether this node wrapper had the same issue: https://github.com/closeio/closeio-node/issues/4?

**Comment by taylorbrooks** [comment]
Interesting. Lemme take a look into this.

**Comment by michaelimstepf** [comment]
Thx. The second line returns 0 results even though there are matches.

**Comment by taylorbrooks** [comment]
What if you do this?
```ruby
client.list_leads('"custom.Multiple once off":false')
```

**Comment by michaelimstepf** [comment]
Bingo! Thanks!

**Comment by michaelimstepf** [comment]
Is there any way to make this work with string interpolation?

```ruby
client.list_leads('"custom.Global ID":#{user.id}')
```

**Comment by taylorbrooks** [comment]
Will it work if you flip the quotes?
```ruby
client.list_leads("'custom.Global ID':#{user.id}")
```

**Comment by michaelimstepf** [comment]
No =(

**Comment by taylorbrooks** [comment]
What if you change your custom field keys by "dasherize-ing" them? That way you wouldn't have to do this single/double quote dance...

```ruby 
client.list_leads("'custom.Global ID':#{user.id}") # vs.
client.list_leads("custom.Global-ID:#{user.id}")
```

**Comment by michaelimstepf** [comment]
That's definitely what I would recommend to someone setting up Close for the first time. We have quite a bit of code and reports where these custom fields are hard coded so I'd have to change that.

I found a way to make it work

```ruby
backend.list_leads('"custom.Global ID":'+user.id.to_s)
```

Thanks for your help!
