### ISSUE TITLE
"You are setting a key that conflicts with a built-in method Hashie::Mash#object_id defined in Kernel. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method."

### ISSUE THREAD

**Issue by stevenmaguire** [taylorbrooks/closeio#39]
A recent build of our project that includes this gem has emitted this Hashie warning.

"You are setting a key that conflicts with a built-in method Hashie::Mash#object_id defined in Kernel. This can cause unexpected behavior when accessing the key via as a property. You can still access the key via the #[] method."

Have you experienced the same?

**Comment by taylorbrooks** [comment]
Yes, I'm debating removing Hashie altogether because of it's memory bloat.

**Comment by stevenmaguire** [comment]
Oh? I am happy to have less memory bloat :)

**Comment by taylorbrooks** [comment]
v3.0.0 removes Hashie and fixes this error. 

The bump to v3.0.0 is a breaking change so test before you integrate.
