### ISSUE TITLE
Advanced Filters API

### ISSUE THREAD

**Issue by TruRooms** [taylorbrooks/closeio#69]
Have you given any thought about how to support the advanced filters API through this gem?

It seems like the Close API has changed quite a bit. We are investing pretty heavily in the Close ecosystem and we are willing to contribute code and time to implement, but this would be a pretty big project.

@taylorbrooks

**Comment by taylorbrooks** [comment]
Yes, willing to support this feature.

Happy to accept PRs or collaborate towards a solution together.

**Comment by TruRooms** [comment]
That sounds great. The request structure for the advanced filters API is pretty dense.

At the basest, we could just supply an endpoint (`client.search`) where you bring your own body.
