### ISSUE TITLE
Support Faraday 2.x

### ISSUE THREAD

**Issue by Roguelazer** [taylorbrooks/closeio#76]
The gem depends on `faraday_middleware`, which means that it only works with Faraday 1.x; it would be swell if it supported Faraday 2.x, too.

**Comment by taylorbrooks** [comment]
Most recent gem version supports Faraday 2.x!

**Comment by Roguelazer** [comment]
It looks like you missed one reference.

```
NameError: uninitialized constant Faraday::Response::Middleware

  class CloseioErrorHandler < Faraday::Response::Middleware
```

If you look at #77, this moved to `Faraday::Middleware` in Faraday 2.x...

**Comment by taylorbrooks** [comment]
Doh! Cutting a new version now.
